# Generated by Django 3.1.2 on 2020-10-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='category',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='Img/%Y/%M/%d'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.TextField(max_length=10),
        ),
    ]
